### ISSUE TITLE
Add debriefing after each level/scenario

### ISSUE THREAD

**Issue by madeleine-b** [systers/powerup-iOS#10]
While the iPod scenario currently has a brief summary of the outcome, there should be a page that goes over the lessons taught in the scenario. For the iPod scenes, this could be talking about how to communicate assertively and use "I" statements. For the unprotected level, this could cover the importance of communication between partners and positivity towards safe sex and that there are high risks from unprotected sex.

**Comment by steminist** [comment]
Text for sex level debriefing: 
"Whether or not Rosie and Marco choose to have sex is completely their decision, as long as there is clear communication, explicit mutual consent and a safe sex policy. In this scenario, since Marco did not have condoms, going home was the correct decision. Unprotected sex can lead to sexually transmitted diseases and unwanted pregnancy. "

We want to make sure that users understand the lessons each play leads to. In this level, the two scenarios would be unprotected sex and Rosie going home.
