### ISSUE TITLE
Addition Of Game Completion Screen.

### ISSUE THREAD

**Issue by SIMRAN1** [systers/powerup-iOS#242]
## Description
As a user, I want to see my karma points at the end of the game so that I know how many karma points I have in total.This feature is implemented in android.

## Mocks

![image](https://user-images.githubusercontent.com/21240014/37851903-98287cc6-2f06-11e8-870b-d1aef04d5f1e.png)

## Acceptance Criteria
When Completion Screen is added.
### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by SIMRAN1** [comment]
@sunjunkie please approve the issue so that I can work on it.

**Comment by sunjunkie** [comment]
@SIMRAN1 Can you complete the required items in the issue template (Update section)?

Also, you are mixing 2 users (user and developer) in the user story.  The user story should be from the viewpoint of the same person --  "As a *user*, I want to *see my karma points at the end of the game* so that *I know how many karma points I have*". 

Please make those changes and then go ahead and work on the issue.

**Comment by SIMRAN1** [comment]
sorry @sunjunkie mam I will fix the issue template and send a pr for it!!

**Comment by sunjunkie** [comment]
You are using the 'vocabmatching_background' for the end screen. If this image is ever changed to something specific for the vocabulary game, it would break the end screen. I suggest that you duplicate the image file, rename it, and then add it as a new image set for the end screen background.

Also, no need for a 'developer' user story. The user's user story is descriptive enough for the issue. The developer story is just a duplicate. And the user is more important than the developer.  :-)
